ip = input("Digite um endereco: ")
print('o ip digitado '+ip+' e valido')
print ('o ip digitado %s e valido' %ip)
print ('o ip %s e valido e possue %s caracteres' %(ip, str(len(ip))))
print ('Numero quebrado %f ' % 41.2345)
